# Generated by Django 2.2.14 on 2023-03-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230302_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='motherboard', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED'), ('REFURBISHED', 'REFURBISHED')], default='NEW', max_length=11),
        ),
        migrations.AddField(
            model_name='item',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='noimg.jpg', height_field=400, upload_to='', width_field=400),
        ),
    ]
