# Generated by Django 2.2.14 on 2023-03-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230303_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='a1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='a2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='a3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
