# Generated by Django 2.2.14 on 2023-03-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230303_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='information',
        ),
        migrations.AddField(
            model_name='item',
            name='description1',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description3',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description4',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description5',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
