# Generated by Django 2.2.14 on 2023-03-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230305_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img2',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img3',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img4',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img5',
            field=models.ImageField(default='no_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('F', 'featured'), ('D', 'danger')], max_length=1),
        ),
    ]
